<?php
/* Reviewer application: field definitions (the server-side whitelist).
   GENERATED from the same spec as the form in reviewer-application.html,
   so the allowed answers match the form exactly. If you change a question
   or an option in the form, change it here too. */
declare(strict_types=1);

const RV_SECTIONS = ['Personal and Professional Information', 'Expertise and Experience', 'Reviewer Availability', 'Supporting Information', 'Reviewer Declaration and Ethical Commitment'];

const RV_FIELDS = [
    'fullName' => ['section' => 1, 'label' => '1. Full Name', 'type' => 'text', 'max' => 120, 'required' => true],
    'title' => ['section' => 1, 'label' => '2. Academic Title / Professional Role', 'type' => 'radio', 'required' => true, 'options' => ['Professor', 'Associate Professor', 'Assistant Professor', 'Senior Lecturer', 'Lecturer', 'Researcher', 'Industry / Professional Expert', 'Other'], 'other' => 'titleOther'],
    'institution' => ['section' => 1, 'label' => '3. Institution / Organisation', 'type' => 'text', 'max' => 200, 'required' => true],
    'department' => ['section' => 1, 'label' => '4. Department / Faculty', 'type' => 'text', 'max' => 200, 'required' => false],
    'country' => ['section' => 1, 'label' => '5. Country', 'type' => 'text', 'max' => 80, 'required' => true],
    'city' => ['section' => 1, 'label' => '6. City', 'type' => 'text', 'max' => 80, 'required' => false],
    'email' => ['section' => 1, 'label' => '7. Email Address', 'type' => 'email', 'max' => 190, 'required' => true],
    'altEmail' => ['section' => 1, 'label' => '8. Alternative Email Address', 'type' => 'email', 'max' => 190, 'required' => false],
    'phone' => ['section' => 1, 'label' => '9. Phone Number (with country code)', 'type' => 'phone', 'required' => true],
    'qualification' => ['section' => 1, 'label' => '10. Highest Academic Qualification', 'type' => 'radio', 'required' => true, 'options' => ['PhD / Doctorate', 'PhD Candidate (in progress)', 'Master\'s Degree', 'Professional Qualification', 'Other'], 'other' => 'qualificationOther'],
    'specialisation' => ['section' => 1, 'label' => '11. Field of Specialisation / Area of Expertise', 'type' => 'textarea', 'max' => 600, 'required' => true],
    'tracks' => ['section' => 2, 'label' => '12. Conference Track(s) Matching Your Expertise', 'type' => 'checkbox', 'required' => true, 'options' => ['Engineering Systems, Technology & Sustainable Solutions', 'Aeronautical Sciences, Engineering & Technology', 'Marine Engineering & Technology', 'Science & English Language Learning', 'Sustainable Buildings & Construction', 'Other'], 'other' => 'tracksOther'],
    'trackDetail' => ['section' => 2, 'label' => '13. Tracks You Can Review', 'type' => 'trackpick', 'required' => true],
    'keywords' => ['section' => 2, 'label' => '14. Expertise Keywords', 'type' => 'keywords', 'required' => true],
    'experience' => ['section' => 2, 'label' => '15. Number of Years of Academic / Professional Experience', 'type' => 'radio', 'required' => true, 'options' => ['Less than 5 years', '5-10 years', '11-15 years', '16-20 years', 'More than 20 years']],
    'publications' => ['section' => 2, 'label' => '16. Approximate Number of Peer-Reviewed Publications', 'type' => 'radio', 'required' => true, 'options' => ['None', '1-5', '6-10', '11-20', '21-40', 'More than 40']],
    'reviewedBefore' => ['section' => 2, 'label' => '17. Have you previously reviewed academic papers?', 'type' => 'radio', 'required' => true, 'options' => ['Yes', 'No']],
    'reviewTypes' => ['section' => 2, 'label' => '18. If yes, please indicate your reviewing experience', 'type' => 'checkbox', 'required' => true, 'options' => ['International journals', 'National journals', 'International conferences', 'National conferences', 'Book chapters / edited volumes', 'Research proposals', 'Other'], 'other' => 'reviewTypesOther', 'showif' => ['reviewedBefore', 'Yes']],
    'profileLink' => ['section' => 2, 'label' => '19. Academic / Professional Profile Link', 'type' => 'url', 'max' => 300, 'required' => false],
    'orcid' => ['section' => 2, 'label' => '20. ORCID iD', 'type' => 'orcid', 'max' => 40, 'required' => false],
    'scholarLink' => ['section' => 2, 'label' => '21. Google Scholar or Scopus Profile Link', 'type' => 'url', 'max' => 300, 'required' => false],
    'hIndex' => ['section' => 2, 'label' => '22. h-index', 'type' => 'number', 'max' => 300, 'min' => 0, 'required' => false],
    'maxPapers' => ['section' => 3, 'label' => '23. Maximum Number of Papers You Can Review', 'type' => 'radio', 'required' => true, 'options' => ['1 paper', '2 papers', '3 papers', '4 papers', '5 or more papers']],
    'timely' => ['section' => 3, 'label' => '24. Can you complete each review within approximately 7-14 days?', 'type' => 'radio', 'required' => true, 'options' => ['Yes', 'No']],
    'cv' => ['section' => 4, 'label' => '25. Curriculum Vitae (CV)', 'type' => 'file', 'required' => true],
    'declaration' => ['section' => 5, 'label' => 'Declaration', 'type' => 'consent', 'required' => true],
    'consentData' => ['section' => 5, 'label' => 'Consent to use of data', 'type' => 'consent', 'required' => true],
    'consentListing' => ['section' => 5, 'label' => 'Consent to be listed on the website', 'type' => 'consent', 'required' => false],
    'applicantName' => ['section' => 5, 'label' => '26. Applicant Name', 'type' => 'text', 'max' => 120, 'required' => true],
];

/* Question "Tracks You Can Review": conference -> track -> topics.
   Same text as the Conference Tracks sections on the conference pages. */
const RV_TRACKS = [
    'Engineering Systems, Technology & Sustainable Solutions' => [
        'ICSETS-1' => ['title' => 'Intelligent Systems, Artificial Intelligence & Automation', 'topics' => ['ICSETS-1-1' => 'Artificial Intelligence and Machine Learning', 'ICSETS-1-2' => 'Fuzzy Systems and Neural Networks', 'ICSETS-1-3' => 'Computer Vision and Image Processing', 'ICSETS-1-4' => 'Natural Language Processing and Generative AI', 'ICSETS-1-5' => 'Unmanned and Autonomous Vehicles (UAV)', 'ICSETS-1-6' => 'Control Systems, Robotics, Autonomous Systems', 'ICSETS-1-7' => 'Multi-Agent and Swarm Systems', 'ICSETS-1-8' => 'Industrial Automation and Smart Control', 'ICSETS-1-9' => 'Human-Computer Interaction (HCI)', 'ICSETS-1-10' => 'AI Applications in Defence, Healthcare, and Industry']],
        'ICSETS-2' => ['title' => 'Electronics, Communications & Embedded Technologies', 'topics' => ['ICSETS-2-1' => 'Analog and Digital Electronics', 'ICSETS-2-2' => 'VLSI Circuits and Semiconductor Technology', 'ICSETS-2-3' => 'FPGA and Embedded Systems Design', 'ICSETS-2-4' => 'Internet of Things (IoT) and wireless sensor network (WSN)', 'ICSETS-2-5' => 'Networking, 5G, and Emerging Communication Technologies', 'ICSETS-2-6' => 'RF and Microwave Circuits and Antennas design', 'ICSETS-2-7' => 'Remote Sensing, Image Processing, and Photonics', 'ICSETS-2-8' => 'Signal Processing and Communication Networks', 'ICSETS-2-9' => 'Sensor Technologies and Smart Instrumentation', 'ICSETS-2-10' => 'Defence electronics and military applications', 'ICSETS-2-11' => 'Biomedical Engineering and Health Science Applications', 'ICSETS-2-12' => 'Laser, Photonics, and Advanced Ordnance Technologies', 'ICSETS-2-13' => 'Nanoscale Technologies for Medical Devices, Diagnostics, and Wearable Health Technologies']],
        'ICSETS-3' => ['title' => 'Sustainable Energy Systems & Green Engineering', 'topics' => ['ICSETS-3-1' => 'Solar Energy Systems and Photovoltaics', 'ICSETS-3-2' => 'Wind and Renewable Energy Technologies', 'ICSETS-3-3' => 'Smart Grids and Energy Management', 'ICSETS-3-4' => 'Energy Storage Technologies', 'ICSETS-3-5' => 'Hydrogen and Fuel Cell Technologies', 'ICSETS-3-6' => 'Power Electronics for Sustainable Energy', 'ICSETS-3-7' => 'Electrification and Green Transportation', 'ICSETS-3-8' => 'Nanotechnology for Sustainability and Environmental Engineering']],
        'ICSETS-4' => ['title' => 'Cybersecurity, Digital Transformation & Advanced Technologies', 'topics' => ['ICSETS-4-1' => 'Cybersecurity and Information Assurance', 'ICSETS-4-2' => 'Critical Infrastructure Protection', 'ICSETS-4-3' => 'Industrial Control Systems (ICS) Security', 'ICSETS-4-4' => 'Cloud and Edge Security', 'ICSETS-4-5' => 'Digital Transformation Strategies', 'ICSETS-4-6' => 'Digital Twins and Smart Infrastructure', 'ICSETS-4-7' => 'Smart Cities and Intelligent Urban Systems', 'ICSETS-4-8' => 'Blockchain and Secure Digital Technologies', 'ICSETS-4-9' => 'Data Governance and Digital Trust', 'ICSETS-4-10' => 'Smart Utilities and Infrastructure Monitoring', 'ICSETS-4-11' => 'Risk Assessment and Cyber Resilience']],
        'ICSETS-5' => ['title' => 'Advanced Manufacturing, Materials & Industrial Technologies', 'topics' => ['ICSETS-5-1' => 'Industry 4.0 and Smart Factories', 'ICSETS-5-2' => 'Additive Manufacturing and 3D Printing', 'ICSETS-5-3' => 'Intelligent Manufacturing and Automation', 'ICSETS-5-4' => 'Advanced Materials and Composites', 'ICSETS-5-5' => 'Functional and Smart Materials', 'ICSETS-5-6' => 'Materials Characterization and Testing', 'ICSETS-5-7' => 'Sustainable Manufacturing Technologies', 'ICSETS-5-8' => 'Product Design and Engineering Innovation', 'ICSETS-5-9' => 'Digital Manufacturing and Simulation', 'ICSETS-5-10' => 'Quality Engineering and Reliability']],
    ],
    'Aeronautical Sciences, Engineering & Technology' => [
        'ICASET-1' => ['title' => 'Aerodynamics, Propulsion & Flight Sciences', 'topics' => ['ICASET-1-1' => 'Compressible and Incompressible Aerodynamics', 'ICASET-1-2' => 'Subsonic, Transonic, Supersonic and Hypersonic Flows', 'ICASET-1-3' => 'Boundary Layer Physics, Turbulence and Flow Control', 'ICASET-1-4' => 'Computational Fluid Dynamics (CFD)', 'ICASET-1-5' => 'Experimental Aerodynamics and Wind Tunnel Testing', 'ICASET-1-6' => 'Aeroelasticity and Fluid-Structure Interaction', 'ICASET-1-7' => 'Aircraft Performance, Stability and Control', 'ICASET-1-8' => 'Flight Mechanics and Flight Dynamics', 'ICASET-1-9' => 'High-Lift Systems and Aircraft Configuration Design', 'ICASET-1-10' => 'Gas Turbine Engines and Propulsion Systems', 'ICASET-1-11' => 'Advanced and Hybrid Propulsion Technologies', 'ICASET-1-12' => 'Aerodynamic Design, Optimization and Simulation']],
        'ICASET-2' => ['title' => 'Avionics, Intelligent Aerospace Systems & Autonomous Technologies', 'topics' => ['ICASET-2-1' => 'Avionics Architectures and Integrated Systems', 'ICASET-2-2' => 'Navigation, Communication and Surveillance Systems', 'ICASET-2-3' => 'Flight Control and Mission Systems', 'ICASET-2-4' => 'Sensors, Sensor Fusion and Signal Processing', 'ICASET-2-5' => 'Embedded Aerospace Systems', 'ICASET-2-6' => 'Autonomous Aerospace Systems', 'ICASET-2-7' => 'Artificial Intelligence and Machine Learning in Aerospace', 'ICASET-2-8' => 'Human-Machine Interaction and Smart Cockpits', 'ICASET-2-9' => 'Aerospace Software Engineering', 'ICASET-2-10' => 'Digital Avionics and Integrated Modular Avionics', 'ICASET-2-11' => 'Electronic Warfare and Mission Systems', 'ICASET-2-12' => 'Aerospace Cybersecurity and Secure Navigation']],
        'ICASET-3' => ['title' => 'Sustainable Aviation & Future Air Mobility', 'topics' => ['ICASET-3-1' => 'Sustainable Aviation Fuels (SAF)', 'ICASET-3-2' => 'Electric and Hybrid-Electric Aircraft', 'ICASET-3-3' => 'Hydrogen-Powered Aviation Systems', 'ICASET-3-4' => 'Advanced Air Mobility (AAM)', 'ICASET-3-5' => 'Urban Air Mobility (UAM)', 'ICASET-3-6' => 'eVTOL Aircraft Technologies', 'ICASET-3-7' => 'Green Airport and Aviation Infrastructure', 'ICASET-3-8' => 'Energy Storage Technologies for Aviation', 'ICASET-3-9' => 'Environmentally Sustainable Aircraft Design', 'ICASET-3-10' => 'Noise and Emissions Reduction Technologies', 'ICASET-3-11' => 'Smart and Connected Aviation Systems', 'ICASET-3-12' => 'Future Air Transportation Concepts']],
        'ICASET-4' => ['title' => 'Aerospace Structures, Materials, Manufacturing & MRO', 'topics' => ['ICASET-4-1' => 'Aerospace Structural Design and Analysis', 'ICASET-4-2' => 'Structural Mechanics and Structural Integrity', 'ICASET-4-3' => 'Lightweight Structures and Composites', 'ICASET-4-4' => 'Advanced Aerospace Materials', 'ICASET-4-5' => 'Smart and Multifunctional Materials', 'ICASET-4-6' => 'Materials Characterization and Testing', 'ICASET-4-7' => 'Fatigue, Fracture and Damage Tolerance', 'ICASET-4-8' => 'Additive Manufacturing and 3D Printing', 'ICASET-4-9' => 'Advanced Manufacturing Technologies', 'ICASET-4-10' => 'Structural Health Monitoring', 'ICASET-4-11' => 'Non-Destructive Testing and Evaluation (NDT/NDE)', 'ICASET-4-12' => 'Maintenance, Repair and Overhaul (MRO)', 'ICASET-4-13' => 'Predictive Maintenance and Lifecycle Management']],
        'ICASET-5' => ['title' => 'Unmanned Aerial Systems (UAS) & Drone Technologies', 'topics' => ['ICASET-5-1' => 'UAS Design and Development', 'ICASET-5-2' => 'Autonomous Flight, Guidance and Control', 'ICASET-5-3' => 'AI and Machine Learning for UAS', 'ICASET-5-4' => 'Computer Vision and Perception Systems', 'ICASET-5-5' => 'Swarm Intelligence and Cooperative UAV Operations', 'ICASET-5-6' => 'Drone Navigation and Mission Planning', 'ICASET-5-7' => 'UAS Sensors, Payloads and Data Systems', 'ICASET-5-8' => 'Beyond Visual Line of Sight (BVLOS) Operations', 'ICASET-5-9' => 'UTM and Airspace Integration', 'ICASET-5-10' => 'UAS Safety and Airworthiness', 'ICASET-5-11' => 'Drone Cybersecurity and Secure Communications', 'ICASET-5-12' => 'Civil, Commercial and Defence Drone Applications', 'ICASET-5-13' => 'Counter-UAS and Airspace Protection Technologies']],
        'ICASET-6' => ['title' => 'Aviation Safety, Operations & Smart Infrastructure', 'topics' => ['ICASET-6-1' => 'Safety Management Systems (SMS)', 'ICASET-6-2' => 'Aviation Risk Assessment and Management', 'ICASET-6-3' => 'Aviation Security and Resilience', 'ICASET-6-4' => 'Aircraft Accident and Incident Investigation', 'ICASET-6-5' => 'Human Factors and Crew Resource Management', 'ICASET-6-6' => 'Airworthiness and Certification', 'ICASET-6-7' => 'Aviation Regulations, Standards and Compliance', 'ICASET-6-8' => 'Air Traffic Management and Air Navigation', 'ICASET-6-9' => 'Airport Planning and Infrastructure', 'ICASET-6-10' => 'Smart Airports and Digital Airport Systems', 'ICASET-6-11' => 'Ground Operations and Airline Management', 'ICASET-6-12' => 'Emergency Preparedness and Crisis Management', 'ICASET-6-13' => 'Aviation Training and Competency Development']],
        'ICASET-7' => ['title' => 'Space Engineering, Technology & Applications', 'topics' => ['ICASET-7-1' => 'Spacecraft and Satellite Systems', 'ICASET-7-2' => 'CubeSats and Small Satellite Technologies', 'ICASET-7-3' => 'Launch Vehicle Systems and Propulsion', 'ICASET-7-4' => 'Orbital Mechanics and Mission Design', 'ICASET-7-5' => 'Space Guidance, Navigation and Control', 'ICASET-7-6' => 'Space Avionics and Communications', 'ICASET-7-7' => 'Space Structures, Materials and Thermal Systems', 'ICASET-7-8' => 'Remote Sensing and Earth Observation', 'ICASET-7-9' => 'Space Robotics and Autonomous Space Systems', 'ICASET-7-10' => 'Space Situational Awareness and Space Traffic Management', 'ICASET-7-11' => 'Space Debris Monitoring and Mitigation', 'ICASET-7-12' => 'Lunar, Planetary and Deep-Space Exploration', 'ICASET-7-13' => 'Emerging and Sustainable Space Technologies']],
    ],
    'Marine Engineering & Technology' => [
        'ICMET-1' => ['title' => 'Sustainable Marine Technologies & Blue-Economy Growth', 'topics' => ['ICMET-1-1' => 'Fuel Cell and Hydrogen Technologies', 'ICMET-1-2' => 'Sustainable Marine Propulsion Systems', 'ICMET-1-3' => 'Hybrid and Electric Marine Power Systems', 'ICMET-1-4' => 'Renewable Energy for Maritime Applications', 'ICMET-1-5' => 'Offshore Wind and Ocean Energy', 'ICMET-1-6' => 'Decarbonization of Shipping', 'ICMET-1-7' => 'Marine Energy Efficiency Technologies', 'ICMET-1-8' => 'Environmental Sustainability in Marine Operations', 'ICMET-1-9' => 'Green Ports and Green Shipping Initiatives', 'ICMET-1-10' => 'Marine Resource Sustainability and Blue Economy Development']],
        'ICMET-2' => ['title' => 'Naval Architecture, Shipbuilding & Marine Structures', 'topics' => ['ICMET-2-1' => 'Ship Design and Optimization', 'ICMET-2-2' => 'Advanced Naval Architecture', 'ICMET-2-3' => 'Lightweight and Composite Marine Structures', 'ICMET-2-4' => 'Ship Hydrodynamics and Performance', 'ICMET-2-5' => 'Autonomous and Unmanned Surface Vessels', 'ICMET-2-6' => 'Smart Ship Systems', 'ICMET-2-7' => 'Ship Propulsion Integration', 'ICMET-2-8' => 'Modular Shipbuilding Technologies', 'ICMET-2-9' => 'Robotics in Shipbuilding', 'ICMET-2-10' => 'Structural Integrity and Lifecycle Management']],
        'ICMET-3' => ['title' => 'Digital Transformation & Intelligent Marine Systems', 'topics' => ['ICMET-3-1' => 'AI-Driven Ship Operations', 'ICMET-3-2' => 'Maritime Automation and Control Systems', 'ICMET-3-3' => 'Smart Navigation Technologies', 'ICMET-3-4' => 'Maritime IoT and Smart Sensing', 'ICMET-3-5' => 'Predictive Maintenance', 'ICMET-3-6' => 'Digital Twins for Maritime Systems', 'ICMET-3-7' => 'Edge Computing for Marine Applications', 'ICMET-3-8' => 'Autonomous Maritime Systems', 'ICMET-3-9' => 'Smart Vessel Management', 'ICMET-3-10' => 'Maritime Data Analytics and Decision Support']],
        'ICMET-4' => ['title' => 'Marine Safety, Environmental Protection & Risk Management', 'topics' => ['ICMET-4-1' => 'Maritime Risk Assessment', 'ICMET-4-2' => 'Safety and Emergency Response', 'ICMET-4-3' => 'Marine Environmental Protection', 'ICMET-4-4' => 'Oil Spill Prevention and Response', 'ICMET-4-5' => 'Structural Health Monitoring', 'ICMET-4-6' => 'Reliability and Resilience of Marine Systems', 'ICMET-4-7' => 'Maritime Surveillance Technologies', 'ICMET-4-8' => 'Search and Rescue Technologies', 'ICMET-4-9' => 'Incident Investigation and Safety Analytics', 'ICMET-4-10' => 'Digital Technologies for Maritime Safety']],
        'ICMET-5' => ['title' => 'Smart Maritime Logistics & Infrastructure Systems', 'topics' => ['ICMET-5-1' => 'Smart Ports and Port Digitalization', 'ICMET-5-2' => 'Maritime Logistics and Supply Chains', 'ICMET-5-3' => 'Autonomous Port Operations', 'ICMET-5-4' => 'Port Automation and Robotics', 'ICMET-5-5' => 'Maritime Asset Tracking and Monitoring', 'ICMET-5-6' => 'Satellite and GNSS Applications', 'ICMET-5-7' => 'Intelligent Transportation and Intermodal Systems', 'ICMET-5-8' => 'Smart Coastal and Maritime Infrastructure', 'ICMET-5-9' => 'Resilient Maritime Logistics Systems']],
    ],
    'Science & English Language Learning' => [
        'ICSELL-1' => ['title' => 'English Language Learning & Digital Pedagogy', 'topics' => ['ICSELL-1-1' => 'Technology-Enhanced Language Learning', 'ICSELL-1-2' => 'AI-Assisted Language Teaching and Learning', 'ICSELL-1-3' => 'Intelligent Tutoring Systems and Educational Chatbots', 'ICSELL-1-4' => 'Mobile and Ubiquitous Language Learning', 'ICSELL-1-5' => 'Immersive Learning Using AR, VR and XR', 'ICSELL-1-6' => 'Digital Storytelling and Gamification', 'ICSELL-1-7' => 'Language Assessment and Automated Feedback', 'ICSELL-1-8' => 'Second Language Acquisition in Digital Environments', 'ICSELL-1-9' => 'Collaborative and Social Language Learning', 'ICSELL-1-10' => 'Curriculum Innovation in English Language Teaching', 'ICSELL-1-11' => 'Teacher Professional Development and Digital Competencies', 'ICSELL-1-12' => 'Inclusive and Accessible Language Education']],
        'ICSELL-2' => ['title' => 'Future Education, Learning Ecosystems & Educational Innovation', 'topics' => ['ICSELL-2-1' => 'Digital Transformation in Education', 'ICSELL-2-2' => 'Smart Classrooms and Future Learning Environments', 'ICSELL-2-3' => 'Educational Innovation and Curriculum Design', 'ICSELL-2-4' => 'Learning Ecosystems and Lifelong Learning', 'ICSELL-2-5' => 'STEM and Interdisciplinary Education', 'ICSELL-2-6' => 'AI Literacy and Digital Literacy', 'ICSELL-2-7' => 'Educational Leadership and Policy', 'ICSELL-2-8' => 'Personalized and Adaptive Learning', 'ICSELL-2-9' => 'Educational Technologies and Learning Platforms', 'ICSELL-2-10' => 'Student Engagement and Success Strategies', 'ICSELL-2-11' => 'Future Skills and Workforce Development', 'ICSELL-2-12' => 'Ethics, Equity and Inclusion in Education']],
        'ICSELL-3' => ['title' => 'Computing Technologies, AI & Learning Analytics', 'topics' => ['ICSELL-3-1' => 'Artificial Intelligence in Education', 'ICSELL-3-2' => 'Learning Analytics and Educational Data Mining', 'ICSELL-3-3' => 'Educational Data Science and Predictive Analytics', 'ICSELL-3-4' => 'Human-Computer Interaction in Learning Environments', 'ICSELL-3-5' => 'Intelligent Learning Systems', 'ICSELL-3-6' => 'Educational Software Design and Development', 'ICSELL-3-7' => 'Cloud-Based Learning Platforms', 'ICSELL-3-8' => 'AI-Driven Assessment and Evaluation', 'ICSELL-3-9' => 'Natural Language Processing for Education', 'ICSELL-3-10' => 'Generative AI for Teaching and Learning', 'ICSELL-3-11' => 'Educational Cybersecurity and Digital Safety', 'ICSELL-3-12' => 'Emerging Technologies for Digital Learning']],
        'ICSELL-4' => ['title' => 'Physical Sciences: Solid-State, Quantum & Materials Research', 'topics' => ['ICSELL-4-1' => 'Solid-State Physics and Semiconductor Technologies', 'ICSELL-4-2' => 'Quantum Science and Quantum Technologies', 'ICSELL-4-3' => 'Quantum Computing and Quantum Communication', 'ICSELL-4-4' => 'Nanomaterials and Nanotechnology', 'ICSELL-4-5' => 'Functional and Smart Materials', 'ICSELL-4-6' => 'Materials Characterization and Testing', 'ICSELL-4-7' => 'Photonics, Optics and Laser Technologies', 'ICSELL-4-8' => 'Energy Materials and Renewable Energy Applications', 'ICSELL-4-9' => 'Computational and Theoretical Physics', 'ICSELL-4-10' => 'Experimental Physics and Advanced Instrumentation', 'ICSELL-4-11' => 'Sensors, Measurement and Detection Systems', 'ICSELL-4-12' => 'Emerging Physics Applications in Engineering and Technology']],
        'ICSELL-5' => ['title' => 'Mathematical Modeling, Computational Science & Applied Analytics', 'topics' => ['ICSELL-5-1' => 'Mathematical Modeling and Simulation', 'ICSELL-5-2' => 'Numerical Methods and Scientific Computing', 'ICSELL-5-3' => 'Optimization and Operations Research', 'ICSELL-5-4' => 'Computational Mathematics', 'ICSELL-5-5' => 'Data Analytics and Statistical Modeling', 'ICSELL-5-6' => 'Machine Learning Foundations and Mathematical AI', 'ICSELL-5-7' => 'Time-Series Analysis and Forecasting', 'ICSELL-5-8' => 'Probability, Statistics and Uncertainty Quantification', 'ICSELL-5-9' => 'Computational Fluid Dynamics and Multiphysics Modeling', 'ICSELL-5-10' => 'Mathematical Methods in Engineering and Physical Sciences', 'ICSELL-5-11' => 'Decision Science and Risk Analysis', 'ICSELL-5-12' => 'Applied Analytics for Complex Systems']],
    ],
    'Sustainable Buildings & Construction' => [
        'ICSBC-1' => ['title' => 'Digital Transformation, AI & Intelligent Construction Systems', 'topics' => ['ICSBC-1-1' => 'Building Information Modeling (BIM)', 'ICSBC-1-2' => 'Digital Twins for Buildings and Infrastructure', 'ICSBC-1-3' => 'Artificial Intelligence in Construction', 'ICSBC-1-4' => 'Autonomous Construction Equipment', 'ICSBC-1-5' => '3D Printed and Additive Construction', 'ICSBC-1-6' => 'Augmented, Virtual and Mixed Reality in Construction', 'ICSBC-1-7' => 'Internet of Things (IoT) and Smart Construction Sites', 'ICSBC-1-8' => 'Big Data Analytics for Construction Management', 'ICSBC-1-9' => 'Cloud Computing and Digital Collaboration Platforms', 'ICSBC-1-10' => 'AI-Based Design Optimization', 'ICSBC-1-11' => 'Automated Quality Control and Inspection', 'ICSBC-1-12' => 'Predictive Maintenance and Asset Management']],
        'ICSBC-2' => ['title' => 'Sustainable Engineering, Resource Efficiency & High-Performance Infrastructure', 'topics' => ['ICSBC-2-1' => 'Sustainable Construction Materials', 'ICSBC-2-2' => 'Green and Low-Carbon Infrastructure', 'ICSBC-2-3' => 'Climate-Resilient Engineering Solutions', 'ICSBC-2-4' => 'Energy-Efficient Building Design', 'ICSBC-2-5' => 'Net-Zero and Positive Energy Buildings', 'ICSBC-2-6' => 'Renewable Energy Integration in Buildings', 'ICSBC-2-7' => 'Water Conservation and Resource Management', 'ICSBC-2-8' => 'Rainwater Harvesting and Greywater Reuse', 'ICSBC-2-9' => 'Circular Economy in Construction', 'ICSBC-2-10' => 'Waste Reduction and Sustainable Material Reuse', 'ICSBC-2-11' => 'Life Cycle Assessment (LCA)', 'ICSBC-2-12' => 'Sustainable Transportation Infrastructure', 'ICSBC-2-13' => 'Value Engineering and Resource Optimization', 'ICSBC-2-14' => 'Sustainable Supply Chains and Procurement', 'ICSBC-2-15' => 'Environmental Impact Assessment and Monitoring']],
        'ICSBC-3' => ['title' => 'Smart, Resilient & Climate-Adaptive Urban Development', 'topics' => ['ICSBC-3-1' => 'Smart Cities and Intelligent Urban Systems', 'ICSBC-3-2' => 'Sustainable Urban Planning and Development', 'ICSBC-3-3' => 'Climate Adaptation and Urban Resilience', 'ICSBC-3-4' => 'Smart Mobility and Transportation Systems', 'ICSBC-3-5' => 'Smart Water and Utility Management', 'ICSBC-3-6' => 'Smart Waste Management Systems', 'ICSBC-3-7' => 'Data-Driven City Management', 'ICSBC-3-8' => 'Urban Digital Twins', 'ICSBC-3-9' => 'Real-Time Urban Monitoring Systems', 'ICSBC-3-10' => 'Disaster Risk Reduction and Preparedness', 'ICSBC-3-11' => 'Nature-Based Solutions for Urban Development', 'ICSBC-3-12' => 'Biophilic Design and Sustainable Communities', 'ICSBC-3-13' => 'Smart Healthcare and Community Infrastructure', 'ICSBC-3-14' => 'Infrastructure Policy, Governance and Planning']],
        'ICSBC-4' => ['title' => 'Structural Assessment, Conservation & Advanced Geomatics', 'topics' => ['ICSBC-4-1' => 'Structural Engineering', 'ICSBC-4-2' => 'Asset Management', 'ICSBC-4-3' => 'Heritage Conservation', 'ICSBC-4-4' => 'Surveying', 'ICSBC-4-5' => 'GIS', 'ICSBC-4-6' => 'Remote Sensing', 'ICSBC-4-7' => 'GeoAI', 'ICSBC-4-8' => 'Land Management', 'ICSBC-4-9' => 'Smart Infrastructure']],
    ],
];

/* Country codes offered in the phone question. */
const RV_DIAL_CODES = [
    'Afghanistan (+93)',
    'Albania (+355)',
    'Algeria (+213)',
    'Andorra (+376)',
    'Angola (+244)',
    'Antigua and Barbuda (+1)',
    'Argentina (+54)',
    'Armenia (+374)',
    'Australia (+61)',
    'Austria (+43)',
    'Azerbaijan (+994)',
    'Bahamas (+1)',
    'Bahrain (+973)',
    'Bangladesh (+880)',
    'Barbados (+1)',
    'Belarus (+375)',
    'Belgium (+32)',
    'Belize (+501)',
    'Benin (+229)',
    'Bhutan (+975)',
    'Bolivia (+591)',
    'Bosnia and Herzegovina (+387)',
    'Botswana (+267)',
    'Brazil (+55)',
    'Brunei (+673)',
    'Bulgaria (+359)',
    'Burkina Faso (+226)',
    'Burundi (+257)',
    'Cabo Verde (+238)',
    'Cambodia (+855)',
    'Cameroon (+237)',
    'Canada (+1)',
    'Central African Republic (+236)',
    'Chad (+235)',
    'Chile (+56)',
    'China (+86)',
    'Colombia (+57)',
    'Comoros (+269)',
    'Congo (+242)',
    'Costa Rica (+506)',
    'Côte d\'Ivoire (+225)',
    'Croatia (+385)',
    'Cuba (+53)',
    'Cyprus (+357)',
    'Czechia (+420)',
    'Democratic Republic of the Congo (+243)',
    'Denmark (+45)',
    'Djibouti (+253)',
    'Dominica (+1)',
    'Dominican Republic (+1)',
    'Ecuador (+593)',
    'Egypt (+20)',
    'El Salvador (+503)',
    'Equatorial Guinea (+240)',
    'Eritrea (+291)',
    'Estonia (+372)',
    'Eswatini (+268)',
    'Ethiopia (+251)',
    'Fiji (+679)',
    'Finland (+358)',
    'France (+33)',
    'Gabon (+241)',
    'Gambia (+220)',
    'Georgia (+995)',
    'Germany (+49)',
    'Ghana (+233)',
    'Greece (+30)',
    'Grenada (+1)',
    'Guatemala (+502)',
    'Guinea (+224)',
    'Guinea-Bissau (+245)',
    'Guyana (+592)',
    'Haiti (+509)',
    'Honduras (+504)',
    'Hong Kong (+852)',
    'Hungary (+36)',
    'Iceland (+354)',
    'India (+91)',
    'Indonesia (+62)',
    'Iran (+98)',
    'Iraq (+964)',
    'Ireland (+353)',
    'Italy (+39)',
    'Jamaica (+1)',
    'Japan (+81)',
    'Jordan (+962)',
    'Kazakhstan (+7)',
    'Kenya (+254)',
    'Kiribati (+686)',
    'Kuwait (+965)',
    'Kyrgyzstan (+996)',
    'Laos (+856)',
    'Latvia (+371)',
    'Lebanon (+961)',
    'Lesotho (+266)',
    'Liberia (+231)',
    'Libya (+218)',
    'Liechtenstein (+423)',
    'Lithuania (+370)',
    'Luxembourg (+352)',
    'Madagascar (+261)',
    'Malawi (+265)',
    'Malaysia (+60)',
    'Maldives (+960)',
    'Mali (+223)',
    'Malta (+356)',
    'Marshall Islands (+692)',
    'Mauritania (+222)',
    'Mauritius (+230)',
    'Mexico (+52)',
    'Micronesia (+691)',
    'Moldova (+373)',
    'Monaco (+377)',
    'Mongolia (+976)',
    'Montenegro (+382)',
    'Morocco (+212)',
    'Mozambique (+258)',
    'Myanmar (+95)',
    'Namibia (+264)',
    'Nauru (+674)',
    'Nepal (+977)',
    'Netherlands (+31)',
    'New Zealand (+64)',
    'Nicaragua (+505)',
    'Niger (+227)',
    'Nigeria (+234)',
    'North Korea (+850)',
    'North Macedonia (+389)',
    'Norway (+47)',
    'Oman (+968)',
    'Pakistan (+92)',
    'Palau (+680)',
    'Palestine (+970)',
    'Panama (+507)',
    'Papua New Guinea (+675)',
    'Paraguay (+595)',
    'Peru (+51)',
    'Philippines (+63)',
    'Poland (+48)',
    'Portugal (+351)',
    'Qatar (+974)',
    'Romania (+40)',
    'Russia (+7)',
    'Rwanda (+250)',
    'Saint Kitts and Nevis (+1)',
    'Saint Lucia (+1)',
    'Saint Vincent and the Grenadines (+1)',
    'Samoa (+685)',
    'San Marino (+378)',
    'Sao Tome and Principe (+239)',
    'Saudi Arabia (+966)',
    'Senegal (+221)',
    'Serbia (+381)',
    'Seychelles (+248)',
    'Sierra Leone (+232)',
    'Singapore (+65)',
    'Slovakia (+421)',
    'Slovenia (+386)',
    'Solomon Islands (+677)',
    'Somalia (+252)',
    'South Africa (+27)',
    'South Korea (+82)',
    'South Sudan (+211)',
    'Spain (+34)',
    'Sri Lanka (+94)',
    'Sudan (+249)',
    'Suriname (+597)',
    'Sweden (+46)',
    'Switzerland (+41)',
    'Syria (+963)',
    'Taiwan (+886)',
    'Tajikistan (+992)',
    'Tanzania (+255)',
    'Thailand (+66)',
    'Timor-Leste (+670)',
    'Togo (+228)',
    'Tonga (+676)',
    'Trinidad and Tobago (+1)',
    'Tunisia (+216)',
    'Turkey (+90)',
    'Turkmenistan (+993)',
    'Tuvalu (+688)',
    'Uganda (+256)',
    'Ukraine (+380)',
    'United Arab Emirates (+971)',
    'United Kingdom (+44)',
    'United States (+1)',
    'Uruguay (+598)',
    'Uzbekistan (+998)',
    'Vanuatu (+678)',
    'Vatican City (+39)',
    'Venezuela (+58)',
    'Vietnam (+84)',
    'Yemen (+967)',
    'Zambia (+260)',
    'Zimbabwe (+263)'
];
